version: "3.8"

services:
    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - db
        env_file: ".env"
    db:
        image: postgres
        ports:
            - "5555:5432"
        env_file: ".env"